apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapi
  template:
    metadata:
      labels:
        app: weatherapi
    spec:
      containers:
      - name: weatherapi
        image: <YOUR_ACR_NAME>.azurecr.io/weatherapi:latest
        ports:
        - containerPort: 80
